server:
  port: 7700
spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: http://127.0.0.1:7701
          predicates:
            - Path=/user/**
        - id: business
          uri: http://127.0.0.1:7702
          predicates:
            - Path=/business/**
        - id: dispatch
          uri: http://127.0.0.1:7703
          predicates:
            - Path=/dispatch/**