server:
  port: 7700
spring:
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: business
          uri: lb://business
          predicates:
            - Path=/business/**
        - id: dispatch
          uri: lb://dispatch
          predicates:
            - Path=/dispatch/**