server:
  port: 7702
  servlet:
    context-path: /business
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      tuberose:
        clock:
          business:
            mapper: trace
spring:
  data:
    redis:
      host: 192.168.1.106
      port: 6379
