spring:
  datasource:
    url: jdbc:mysql://192.168.1.106:3306/clock?characterEncoding=UTF8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
